INSERT INTO TableA (ID,AGE,NAME) VALUES (1,12,'asd');
INSERT INTO TableA (ID,AGE,NAME) VALUES (1,12,    'asd');
INSERT INTO TableA (ID,AGE,NAME) VALUES (1,12,'asd');
INSERT INTO TableA (ID,AGE,NAME) VALUES (1,12    ,'asd');

INSERT INTO TableA (ID,AGE) VALUES (100,12);
INSERT INTO TableA (ID,AGE) VALUES (101,12);

INSERT INTO TableA (ID,AGE,NAME) VALUES (4,12,'asd');
INSERT INTO TableA (ID,AGE,NAME) VALUES (5,12,'asd');

INSERT INTO TableA (ID,AGE) VALUES (102,12);